spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-lab-db
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/movie-lab-db
    user: postgres
    password: postgres
    locations: classpath:db/migration


